### ISSUE TITLE
Make it possible for an account to update publications

### ISSUE THREAD

**Issue by asgeir-eth** [gnosis/tabula#10]
An account with the `publication/update` permission to a publication, should be able to update/overwrite the publication's properties.

Can use the same form as when creating a publication, just pre-populate it with the publication to be updated.

- [x] Subgraph
- [x] App
- [x] Design

**Comment by cedricwaxwing** [comment]
Design: https://www.figma.com/file/IaimIfw2pXyR9PlQqdo6M2/Tabula?node-id=192%3A2526

If the user has permissions, they can edit the publication in the "Settings" tab
