### ISSUE TITLE
More contextual toast popups

### ISSUE THREAD

**Issue by cedricwaxwing** [gnosis/tabula#119]
Ideally these UI can offer more context as to what's happening/happened:

>ideally (but lower priority) we would be able to show some more contextual information in these toasts like: "Transaction execution is complete. Your publication settings have been updated. (etherscan link) (close)".

Mentioned:
- https://github.com/gnosis/tabula/pull/115#pullrequestreview-1013843105

**Comment by cedricwaxwing** [comment]
Temporarily reopening to make sure we confirm it's complete.

**Comment by juliopavila** [comment]
covered https://github.com/gnosis/tabula/pull/228
