### ISSUE TITLE
Make it possible for a user to view a list of articles posted in a publication

### ISSUE THREAD

**Issue by asgeir-eth** [gnosis/tabula#13]
Make it possible for a user to browse a publication.

Should include the publication info and the articles posted to the publication.

- [x] App
- [x] Design

It should be possible to get directly to a publication via a URL. Something like: `/publication/{publicationId}`. This should not require or "push" a reader to connect a wallet. Should be browsable for "web2 users".

**Comment by cedricwaxwing** [comment]
Design: https://www.figma.com/file/IaimIfw2pXyR9PlQqdo6M2/Tabula?node-id=192%3A2360
