### ISSUE TITLE
Footnotes create link that replaces existing routing

### ISSUE THREAD

**Issue by cedricwaxwing** [gnosis/tabula#146]
The markdown footnotes work correctly in implementation (the link is created and the footnote is located in the footer of the post). However, the url for the link replaces the other routing information and just replaces it with the anchor ID of the footnote.

<img width="1361" alt="image" src="https://user-images.githubusercontent.com/80348806/180041838-1edbe9d0-dde1-4225-8db5-14c46910a192.png">

We need to append the anchor ID to the exisitng URL instead of replacing it.

**Comment by juliopavila** [comment]
@cedricwaxwing  @auryn-macmillan  Solved here #167 

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/19823989/183307728-b24055a6-caf8-42ce-9d74-95d88e62b544.png">
