### ISSUE TITLE
Cannot post to Mainnet or Rinkeby

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/tabula#165]
**Describe the bug**
Unable to post to mainnet or Rinkeby (perhaps other networks using Infura as well)

**To Reproduce**
1. Navigate to, or create, a publication on Mainnet or Rinkeby where you have posting permissions.
2. Draft a new post.
3. Click "publish"
4. Notice the `Article Is A Required Field` error underneath the draft. 
![image](https://user-images.githubusercontent.com/8453294/182142542-66e7630f-785d-49e5-86b0-9010eb4bebed.png)

**Expected behavior**
When you click publish, it should trigger a metamask popup to publish your article.

**Comment by juliopavila** [comment]
Solved here https://github.com/gnosis/tabula/issues/163
