### ISSUE TITLE
Pin from local IPFS node

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/tabula#176]
**Is your feature request related to a problem? Please describe.**
Tabula currently provide several options for pinning IPFS data (see the image below), however we do not give the user the option to use a local IPFS node.
![image](https://user-images.githubusercontent.com/8453294/198586105-d87e9c11-0df1-4a72-8a13-ba22f2703734.png)

**Describe the solution you'd like**
We should allow users to select:
- [ ] a local node as a pinning option
- [ ] a custom node running elsewhere
- [ ] 🌮 (taco bonus) allow users to select multiple concurrent pinning options, for redundancy (so they could, for example, have a local node and a pinning service both pinning everything)

**Comment by cedricwaxwing** [comment]
Captured in #127
