### ISSUE TITLE
Integrate rich text/media for better UX

### ISSUE THREAD

**Issue by cedricwaxwing** [gnosis/tabula#180]
**Is your feature request related to a problem? Please describe.**
Currently, the user must write their article in markdown, and they also must provide their own link for images. This is a major barrier for many users.

**Describe the solution you'd like**
A simple rich text editor that directly uploads media to ipfs for the user when the article is published.

**Additional context**
I've mapped out a lot of this flow here: 
https://www.figma.com/file/IaimIfw2pXyR9PlQqdo6M2/Tabula?node-id=1116%3A2197&t=3pePjWqFfpRtjSiF-1

Here's a quick example of what the rich editor might look like:
![image](https://user-images.githubusercontent.com/80348806/208465280-43928196-9850-4730-b02e-1659d25f9fc8.png)

I'd recommend we use an existing library to handle the rich text. Something like this (or similar) would work great: https://github.com/JefMari/awesome-wysiwyg#for-react

**Comment by juliopavila** [comment]
covered https://github.com/gnosis/tabula/pull/228
