### ISSUE TITLE
Design updates

### ISSUE THREAD

**Issue by cedricwaxwing** [gnosis/tabula#183]
https://www.figma.com/file/IaimIfw2pXyR9PlQqdo6M2/Tabula?node-id=666%3A1921&t=6tz0sOxy4R13cPwD-1

**Comment by cedricwaxwing** [comment]
![image](https://user-images.githubusercontent.com/80348806/212753680-8cdd68ac-4912-4a44-ae53-42ec0025a258.png)

**Comment by juliopavila** [comment]
covered here https://github.com/gnosis/tabula/pull/228
