### ISSUE TITLE
General refactoring

### ISSUE THREAD

**Issue by manboy-eth** [gnosis/tabula#192]
It is starting to get hard to navigate the codebase. To improve this, here are some areas that require refactoring:

- [x] `Post` and `Article` is used interchangeably in the codebase. We must decide on one and stick to it. BTW: in the Poster actions, it's referred to as `Articles`, this can not easily change (without invalidation of all articles posted so far), so no matter what we decide, in the actual Poster actions, it will be referred to as articles.
- [x] The naming of views (in `packages/app/src/components/views/publication`) is unclear.
**Views to consider**:
- `packages/app/src/components/views/publication/ArticleTabs.tsx`- not a view? We must move it to the appropriate place.
- `packages/app/src/components/views/publication/ArticleView.tsx` - perhaps needs renaming (based on the first point).
- `packages/app/src/components/views/publication/CreatePostView.tsx` - perhaps needs renaming (based on the first point).
- `packages/app/src/components/views/publication/PermissionView.tsx` - ok.
- `packages/app/src/components/views/publication/PreviewPostView.tsx` - this is not really a preview, it's a step in the create post flow. This should not have been its own view, however, this is going to be removed (in #93), but for now, rename it to `CreatePostView2`?
- `packages/app/src/components/views/publication/PublicationPostView.tsx`- perhaps renamed to `PublicationView`?
- `packages/app/src/components/views/publication/PublishView.tsx` - this lists the publications where the user has permission and lets the user create new publications. Perhaps rename it to `PublicationsView`?

- [x] Rename Post to Article everywhere (except what's prevented the user in the UI, that's up to @cedricwaxwing).

**Comment by cedricwaxwing** [comment]
It doesn't matter to me, so if Article is more consistent from a technology standpoint, it's fine to use that. 👍
