### ISSUE TITLE
No spellchecking in browser

### ISSUE THREAD

**Issue by cedricwaxwing** [gnosis/tabula#234]
There's likely a third-party spell checker that we can use to spell check content when in edit view.

**Comment by auryn-macmillan** [comment]
Most browsers have a baked in spell-checker.
For example, if I missssspell something while I'm commenting on GitHub, my browser highlights the text. So I'm guessing you can probably get this for free depending on properties on the text input.

![image](https://github.com/gnosis/tabula/assets/8453294/44748315-ec35-4a54-8877-d33650f7fa4d)

**Comment by auryn-macmillan** [comment]
I notice that spellcheck works in the the title input, but not in the body.
[Screencast from 07-19-2023 11:19:23 AM.webm](https://github.com/gnosis/tabula/assets/8453294/b2f47d42-7a09-4016-858a-cf8beb71257b)

**Comment by auryn-macmillan** [comment]
I was able to make spellchecking work by adding `spellcheck="true"` to this element in the browser
![image](https://github.com/gnosis/tabula/assets/8453294/fcc916f3-0256-4221-a4f1-04929591070b)
