### ISSUE TITLE
Stop relying exclusively on Infura for IPFS

### ISSUE THREAD

**Issue by manboy-eth** [gnosis/tabula#27]
We should check if there is a local provider available, if not, we can check if Infura is accessible, if not, we spin up a js-ipfs node.

Check this link for hardcoded `ipfs.infura.io` URLs: https://github.com/gnosis/tabula/search?q=%22ipfs.infura.io%22

We do not want Tablua to be easy to censor ;)

**Comment by manboy-eth** [comment]
**The current state**
Upload:
- we use Infura API
- then pinning

Download:
- we use Infura Gateway.

We should, in both cases use the user's locale IPFS node, but fallback to the Infura services.

**The state that we want**
Upload:
- if a user has specified an IPFS node URL we use that (requires UI).
- if not, we use a locale default IPFS node URL `localhost:5001`.
*Investigate if there is a way of getting the browser IPFS URL if it's configured via something like the IPFS companion or Brave. If that is possible use that instead of the two options mentioned above.*
- else we use Infura API
- then pinning

Download:
- we use `ipfs://` if possible.
- else we use Infura Gateway.

**Comment by manboy-eth** [comment]
@cedricwaxwing: we need UI for letting the user specify an IPFS URL.

How it currently works: 
If the user has a running IPFS node at the default URL `http://localhost:5001/api/v0`, then we use that. 
If that is not available we fall back to Infura.

What we need:
In addition to the above, the user should be able to specify a custom IPFS node URL.
If a custom IPFS URL is set, then we use that instead.

For me, it would make sense if this was an option in the "address dropdown menu", like "Update Pinning Service", we could add "Update IPFS Node".  The pop-up needs to explain that if no URL is specified it first tries to connect to a locale IPFS node at the default endpoint (`http://localhost:5001/api/v0`), if that is not available, it will connect to Infura. It also needs a text box for letting the user input a URL.

**Comment by cedricwaxwing** [comment]
@manboy-eth I've taken a stab here. Let me know if this works or needs updating:

Modal popup for Updating IPFS Node:
https://www.figma.com/file/IaimIfw2pXyR9PlQqdo6M2/Tabula?node-id=1330%3A4710&t=TNzdtzW1Jl2zbKRc-4
![image](https://user-images.githubusercontent.com/80348806/213779455-0bb2312d-4b56-4d60-b00f-d2bcb9a74436.png)


And the updated dropdown (ignore the other changes, as those can be captured in #183 ):
https://www.figma.com/file/IaimIfw2pXyR9PlQqdo6M2/Tabula?node-id=1153%3A6497&t=TNzdtzW1Jl2zbKRc-4
![image](https://user-images.githubusercontent.com/80348806/213779118-fe8eab67-227f-4ba8-8414-fe4baa12d791.png)

**Comment by juliopavila** [comment]
> **The current state** Upload:
> 
> * we use Infura API
> * then pinning
> 
> Download:
> 
> * we use Infura Gateway.
> 
> We should, in both cases use the user's locale IPFS node, but fallback to the Infura services.
> 
> **The state that we want** Upload:
> 
> * if a user has specified an IPFS node URL we use that (requires UI).
> * if not, we use a locale default IPFS node URL `localhost:5001`.
>   _Investigate if there is a way of getting the browser IPFS URL if it's configured via something like the IPFS companion or Brave. If that is possible use that instead of the two options mentioned above._
> * else we use Infura API
> * then pinning
> 
> Download:
> 
> * we use `ipfs://` if possible. (not possible until there is some fix for [Fetch API with IPFS url's are blocked by cross-site tracking prevention brave/brave-browser#18204](https://github.com/brave/brave-browser/issues/18204) , will need to either use the Gateway or the connected `ipfs http clien`).
> * else we use Infura Gateway.

@manboy-eth About the download process, I think, for now, we're going to use `IPFS Gateway` because the `Infura Public Gateway` is no longer available https://docs.infura.io/infura/networks/ipfs/how-to/access-ipfs-content/public-gateway, the only way to use it is creating a dedicated server
