### ISSUE TITLE
Connect buttons silently fail if your wallet is on an unsupported network.

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/tabula#56]
When you hit "Connect Wallet" and then select "Metamask" if metamask is connected to an unsupported network.
We should include a prompt to switch to a supported network, including a list of the supported networks.

**Comment by asgeir-eth** [comment]
Thank you, @auryn-macmillan 🙏 

Expanding a bit on this:

**When a user connects a wallet from the Tabula landing page:**
- [ ] If the user's wallet is connected to a supported network, we use that.
- [ ] If the user's wallet is connected to an unsupported network, we list the supported networks and ask the user to click or select one of those. Once the user has selected, we ask the wallet to change the network. @cedricwaxwing: we need a design for this.

**When a user connects a wallet from an article or a publication page:**
- [ ] If the user's wallet is connected to the same network as where the publication lives, we use that.
- [ ] If the user's wallet is connected to a different network, we ask the wallet to change the network to the one where the publication resides.

Sample implementations, see: https://github.com/NoahZinsmeister/web3-react/blob/main/packages/example-next/components/ConnectWithSelect.tsx

**Also:**
- [ ] Once the network is changed, we need to change the network-specific subgraph URL.

**Comment by cedricwaxwing** [comment]
Adding one more here since it's semi-related. If you click connect wallet and then select Metamask, but don't have Metamask extension on your browser, it fails silently as well.

- [ ] If the user attempts to connect to Metamask without the extension installed, display a message saying "You'll need to install MetaMask to continue. Once you have it installed, go ahead and refresh the page."

**Comment by auryn-macmillan** [comment]
> If the user attempts to connect to Metamask without the extension installed, display a message saying "You'll need to install MetaMask to continue. Once you have it installed, go ahead and refresh the page."

@cedricwaxwing, perhaps it would be better to just hide metamask as an option if no injected web3 is detected?
