### ISSUE TITLE
Info Toast UI should show on transaction trigger instead of success.

### ISSUE THREAD

**Issue by cedricwaxwing** [gnosis/tabula#60]
Mentioned here: https://discord.com/channels/@me/930504209403633704/971103584332709939

When you update the permissions, the indexing (info) and success message both show at the same time, on success. The details link only shows on the success notice, but it's ideal to show this on the indexing status toast message.

![image](https://user-images.githubusercontent.com/80348806/166564345-14d7c14f-e74d-4f2e-bd49-c38b0ce5a33e.png)

**Comment by auryn-macmillan** [comment]
Should we also have a toast notification to show that indexing is complete?

**Comment by cedricwaxwing** [comment]
>Should we also have a toast notification to show that indexing is complete?

Good point!
