### ISSUE TITLE
Don't show an error when uploading a file to IPFS that is already pinned

### ISSUE THREAD

**Issue by manboy-eth** [gnosis/tabula#68]
Don't show an error when uploading to IPFS a file that is already pinned. 

~~Instead, we can show an info notification saying `The file {fileName} is already pinned`.~~

**Comment by auryn-macmillan** [comment]
We probably don't need to show anything at all here, right? Or, if we would normally show a success notification, then just show the same notification. Success because we pinned it vs success because it was already pinned are equivalent from the user's perspective.
