### ISSUE TITLE
Make it possible to give an account permissions to a publication

### ISSUE THREAD

**Issue by asgeir-eth** [gnosis/tabula#8]
An account that has the `publication/permissions` permission should be able to give another account permissions to the publication via the `publication/permissions` action (https://github.com/gnosis/tabula#set-publication-permissions).

Display the same form as when creating an article, just pre-populate it with the article to be updated.

- [x] Subgraph
- [x] App
- [x] Design

**Comment by cedricwaxwing** [comment]
Design: https://www.figma.com/file/IaimIfw2pXyR9PlQqdo6M2/Tabula?node-id=219%3A2038
The user can view all accounts that have permissions to the publication. Add a new permission by clicking "New Permission" and filling out the form. Clicking "edit" on an existing permission will bring up the same form with data inside. The address is not editable. You can also delete the permission from this view.

**Comment by juliopavila** [comment]
Done and merged
