### ISSUE TITLE
Remove "continue reading" button

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/tabula#82]
The "continue reading" button on the publication view is redundant and the copy is weird. Let's remove the button altogether.

**Comment by cedricwaxwing** [comment]
@auryn-macmillan I initially planned on having an excerpt from the post (vs a description), so the "Continue Reading" made a bit more sense before 😆

I do still like how it carves out a home for the conditionally visible "Edit Post" button, and would prefer to keep something there if possible to contrast it.
<img width="635" alt="image" src="https://user-images.githubusercontent.com/80348806/169598409-1431f046-618a-4479-80ba-26088a90dc4f.png">

How do you feel about keeping the button, but renaming to "View >" or "Read Post >"?

**Comment by auryn-macmillan** [comment]
"View Post" or "Read Post" would be fine, although I'm not overly concerned about leaving space for the edit button since that's only visible to users with permissions. Most users will only see the "Read Post" button.
