### ISSUE TITLE
Add multiple authors to posts

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/tabula#84]
On the subgraph, we can define multiple authors on one post. It would be really nice to expose this feature in the app. #83 is also related.

**Comment by cedricwaxwing** [comment]
https://www.figma.com/file/IaimIfw2pXyR9PlQqdo6M2/Tabula?node-id=701%3A2188

![image](https://user-images.githubusercontent.com/80348806/171030308-c6873836-9e62-474b-a7d7-d91d3bece49b.png)
