### ISSUE TITLE
Add back / cancel button on article edit view

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/tabula#86]
Once you start editing an article, it's not immediately obvious that you can cancel the action by navigating away. We should explicitly provide a cancel or back button.

**Comment by cedricwaxwing** [comment]
https://www.figma.com/file/IaimIfw2pXyR9PlQqdo6M2/Tabula?node-id=666%3A1922
![image](https://user-images.githubusercontent.com/80348806/169606090-45f2414e-90bd-4a40-9b93-51321042e160.png)
