### ISSUE TITLE
Easy way to get back to publish view

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/tabula#90]
The "publish" view that you land on after authenticating is the the only place you can launch a new publication or switch between existing publication in which you hold permissions. But there is no route back to it once you leave. We should add a route back to it (perhaps from the dropdown menu in the nav bar).

Also worth noting that this page could become the basis for an account page.
#83, #84, and #85 are related.

**Comment by cedricwaxwing** [comment]
https://www.figma.com/file/IaimIfw2pXyR9PlQqdo6M2/Tabula?node-id=539%3A2530
