### ISSUE TITLE
Consolidate article fields into one edit view

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/tabula#93]
Currently, there are two views when publishing or editing an article; one for the title and body, and one for the image, description, and tags.

These should be consolidated into one view, along with an option to preview the post before publishing (mostly to catch markdown errors before publishing).

**Comment by RMBLRX** [comment]
One thing that would be a cool option for consolidating this stuff would be through YAML frontmatter, maybe through a source view or something.  New posts could even have a frontmatter template to make sure all the necessary fields are specified, but then other bits of superfluous fields could be included at the author's discretion: items for future usage like tags and categories, but also arbitrary bits of info for posterity's sake.  One thought I had is that if an image is specified by filename in the frontmatter, the user could be prompted to upload an image in the course of publication which will be given that filename upon upload.

This approach would also make room for the optional inclusion of a publication date, which might differ from the when a piece was published or revised on Tabula.

**Comment by cedricwaxwing** [comment]
Includes: #183

**Comment by cedricwaxwing** [comment]
Reference Ghosts's collapsable window on side that's not content related.
![image](https://user-images.githubusercontent.com/80348806/212749503-1aea78f5-780e-43ac-9b93-06741a21e9b7.png)

**Comment by juliopavila** [comment]
covered here https://github.com/gnosis/tabula/pull/228
