### ISSUE TITLE
Delete preview image from post

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/tabula#94]
There is currently no way to delete a preview image from a post, you can only replace it with another image. We should add a way to remove the image entirely.

**Comment by cedricwaxwing** [comment]
@juliopavila let's swap out the edit button here for the delete button (as shown).

![image](https://user-images.githubusercontent.com/80348806/169605402-7e33dc29-53f3-4b5f-bf35-ae2ae540b10e.png)
https://www.figma.com/file/IaimIfw2pXyR9PlQqdo6M2/Tabula?node-id=666%3A2218

Then we can add an onClick to the actual image, along with a subtle hover effect:

```
thumbnailClass: {
  cursor: "pointer",
  transition: "opacity 0.25 ease-in-out",
  "&:hover": {
    opacity: 0.8,
  }
```
