### ISSUE TITLE
It's not obvious that users should press enter after each tag

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/tabula#95]
It's not obvious that users should press enter after entering each tag. As a result, some users may accidentally enter their tags incorrectly (in a comma separated list, for example).

**Comment by cedricwaxwing** [comment]
I think we should swap out the current UI with something similar to the "Multi-select text input" here:
https://react-select.com/creatable

**Comment by auryn-macmillan** [comment]
Agreed

**Comment by auryn-macmillan** [comment]
Closing as this issue has gone stale.
