### ISSUE TITLE
Remove publication title from above description in editor

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/tabula#99]
In the editor, the publication title is listed above the preview text.
We should remove that title or replace it with "Description".
![image](https://user-images.githubusercontent.com/8453294/169339565-f53c8992-75e4-4141-a174-36cc89f1e1a4.png)

**Comment by cedricwaxwing** [comment]
https://www.figma.com/file/IaimIfw2pXyR9PlQqdo6M2/Tabula?node-id=666%3A1922
